//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWEBApplication.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddTypeMaster
    {
        public int AddTypeId { get; set; }
        public string AddTypeName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ValidFor { get; set; }
        public Nullable<int> countryId { get; set; }
    }
}
