//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWEBApplication.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSecificationsPosted
    {
        public int SSPId { get; set; }
        public Nullable<int> SpecId { get; set; }
        public string ValuePosted { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ServiceAdMasterId { get; set; }
    }
}
