//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWEBApplication.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSpecification
    {
        public int SpecId { get; set; }
        public string SpecName { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> ControlType { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<int> RangeValue { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string SpecType { get; set; }
    }
}
