//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWEBApplication.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAdMaster
    {
        public int ServiceAdMasterId { get; set; }
        public string AdTitle { get; set; }
        public string AboutTheCompany { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<int> AdOwner { get; set; }
        public Nullable<int> LastmodifiedBy { get; set; }
        public Nullable<int> LastmodifiedOn { get; set; }
        public Nullable<int> AddTypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<int> PriorityNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDateTo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Location { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsContactDetailsShown { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string PageUrl { get; set; }
        public string ServicesProvided { get; set; }
        public string FoundedYear { get; set; }
        public string NoOfEmployees { get; set; }
        public string WorkingDays { get; set; }
        public string BusinessAddress { get; set; }
        public Nullable<int> OpeningDayId { get; set; }
        public string FaceBookLink { get; set; }
        public string googlePlusLink { get; set; }
        public string twitterLink { get; set; }
        public string googleMapLink { get; set; }
        public string TSDegreeView { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<decimal> CurrentRating { get; set; }
    }
}
