//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWEBApplication.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReview
    {
        public int ReviewId { get; set; }
        public Nullable<int> ServiceAdMasterId { get; set; }
        public Nullable<int> ReviewBy { get; set; }
        public string ReviewText { get; set; }
        public Nullable<System.DateTime> ReviewOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Rating { get; set; }
    }
}
